### ISSUE TITLE
Map your work guide - name 'gtfs' is not defined

### ISSUE THREAD

**Issue by gianlucarea** [Bondify/gtfs_layers#27]
Map your work guide about the Stop frequencies using gtfs.map_gdf. 
I've been following the guide you don't define gtfs anywhere.
Thanks

**Comment by Bondify** [comment]
hi @gianlucarea I think "gtfs" refers to the feed class. In the guide it is defined as `feed = Feed(gtfs_path)`. My guess is that I forgot to change "gtfs" for "feed" in that section. Try with `feed.map_gdf` instead.
